name: mohally
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^1.1.6
  pin_code_fields: ^7.3.0
  flutter_rating_bar: ^4.0.0
  flutter_svg_provider: ^1.0.3
  dotted_border: 2.0.0+3
  flutter_staggered_grid_view: ^0.4.1
  intl: ^0.18.1
  get: ^4.6.6
  pinput: ^2.2.31
  carousel_slider: ^4.0.0
  gap: ^3.0.1
  flutter_credit_card: ^4.0.1
  email_validator: ^2.1.17
  vertical_tabs_flutter: ^1.0.0
  country_code_picker: ^3.0.0
  http: ^0.13.6
  fluttertoast: ^8.2.2
  shared_preferences: ^2.2.0
  image_picker: ^0.8.7
  scratcher: ^2.5.0
  flutter_widget_from_html: ^0.9.1
  flutter_html: ^3.0.0-beta.2
  flutter_fortune_wheel: ^1.3.0
  audioplayers: ^5.1.0
  loading_animation_widget: ^1.2.0+4
  easy_localization: ^3.0.3
  google_fonts: ^4.0.4
  dio: ^5.4.0
  sealed_countries: ^1.1.0
  provider: ^6.1.1
  geolocator: ^10.1.0
  location: ^5.0.3
  permission_handler: ^11.2.1
  geocoding: ^2.1.1
  flutter_geocoder: ^0.2.2-nullsafety
  pull_to_refresh: ^2.0.0
  virtual_keyboard_multi_language: ^1.0.3
  flutter_countdown_timer: ^4.1.0



















dev_dependencies:
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/audio/
    
  fonts: 
    - family: League Spartan
      fonts: 
        - asset: assets/fonts/LeagueSpartanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/LeagueSpartanBold.ttf
          weight: 700
        - asset: assets/fonts/LeagueSpartanMedium.ttf
          weight: 500
        - asset: assets/fonts/LeagueSpartanRegular.ttf
          weight: 400
        - asset: assets/fonts/LeagueSpartanLight.ttf
          weight: 300
    - family: Jost
      fonts: 
        - asset: assets/fonts/JostRegular.ttf
          weight: 400
        - asset: assets/fonts/JostRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/JostSemiBold.ttf
          weight: 600
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterExtraBold.ttf
          weight: 800
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
    - family: Almarai
      fonts: 
        - asset: assets/fonts/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai-ExtraBold.ttf
        - asset: assets/fonts/Almarai-Light.ttf
        - asset: assets/fonts/Almarai-Regular.ttf

